### ISSUE TITLE
Migration to actix_web 1.0 

### ISSUE THREAD

**Issue by AnderEnder** [GiantPlantsSociety/diamond#246]
actix-web API was changed, which requires changes in application and the code

**Comment by AnderEnder** [comment]
Currently the tests for extractors `FindQuery` and `RenderQuery` are falling:

https://github.com/GiantPlantsSociety/diamond/pull/227

**Comment by sergey-melnychuk** [comment]
Looking into it

**Comment by sergey-melnychuk** [comment]
Blocked by https://github.com/GiantPlantsSociety/diamond/issues/247

**Comment by sergey-melnychuk** [comment]
Unblocked, still looking

**Comment by andy128k** [comment]
Done in #227
