### ISSUE TITLE
Build failed: Could not compile `rrd2whisper`

### ISSUE THREAD

**Issue by sergey-melnychuk** [GiantPlantsSociety/diamond#247]
Reproduced on Linux and on Mac OS.

`uname -a`
`Darwin MacBook-Air.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`
`Linux instance-1 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux`

`rustc -V`
both `rustc 1.36.0 (a53f9df32 2019-07-03)`

Cause:
```
$ cargo build
<snip>
error: linking with `cc` failed: exit code: 1
  = note: /usr/bin/ld: cannot find -lrrd
          collect2: error: ld returned 1 exit status
<snip>
```

Linker cannot find shared library `rrd`. Something isn't right.

**Comment by sergey-melnychuk** [comment]
Switching to `nightly` gets same result, build fails.

**Comment by loony-bean** [comment]
Yeah this needs to be documented. Sorry for confusion.
You need to install rrdtool, see [here](https://github.com/GiantPlantsSociety/diamond/blob/master/.travis.yml#L25).

**Comment by sergey-melnychuk** [comment]
@loony-bean , thank you!
Prepared https://github.com/GiantPlantsSociety/diamond/pull/248.
