### ISSUE TITLE
Feature gate for rrdtool

### ISSUE THREAD

**Issue by loony-bean** [GiantPlantsSociety/diamond#269]
Put [rrdtool](https://oss.oetiker.ch/rrdtool/index.en.html) related components under feature gate, since they are not mandatory for the project.

**Comment by AnderEnder** [comment]
@loony-bean, do you have examples how to do it?

**Comment by loony-bean** [comment]
I meant [conditional compilation](https://doc.rust-lang.org/1.30.0/book/first-edition/conditional-compilation.html), e.g. like [here](https://github.com/bluss/indexmap/blob/master/Cargo.toml#L42).

**Comment by AnderEnder** [comment]
This is not the case. It requires a conditional workspace crate compilation. I found the only way with  `members` vs `default-members` in Cargo.toml(#296)

**Comment by loony-bean** [comment]
Got it, closing
