### ISSUE TITLE
Run cargo check in CI pipeline

### ISSUE THREAD

**Issue by loony-bean** [GiantPlantsSociety/diamond#270]

**Comment by AnderEnder** [comment]
Project became quite huge, so it slows down the CI.

**Comment by loony-bean** [comment]
Yes, but have this done #269 we can shave off some 400+ seconds to spend
https://travis-ci.com/GiantPlantsSociety/diamond/jobs/220280131#L104

**Comment by andy128k** [comment]
So, do you want to remove RRD? What is a point to have a code but not test it?

**Comment by loony-bean** [comment]
I'm looking for ways to speed up CI cycles without compromising test coverage. Open to any ideas. The `cargo check` could help failing a bit faster in some cases.

**Comment by andy128k** [comment]
Create PR and check.

**Comment by AnderEnder** [comment]
> The cargo check could help failing a bit faster in some cases.
This is a very rare case, while additional compile time was added to every build. That is why it was removed from CI
